name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Configure npm authentication
      - name: Configure npm authentication
        run: |
          echo "@vannatta-software:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ GITHUB_TOKEN }}" >> ~/.npmrc

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the TypeScript project
      - name: Build project
        run: npm run build

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
