name: Publish Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Lerna needs full history for conventional commits
          token: ${{ secrets.DEPLOY_TOKEN }} # Use DEPLOY_TOKEN for write access

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: npm install

      - name: Build All Packages
        run: npm run build --workspaces

      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      - name: Set up Git credentials
        run: |
          echo "https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com" > ~/.git-credentials
          git config --global credential.helper store

      - name: Lerna Versioning
        run: npx lerna version --conventional-commits --yes
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Wait for npm propagation
        run: sleep 30

      - name: Lerna Publish
        run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
