name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      # Authenticate with GitHub App Token
      - name: Authenticate with GitHub App Token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACCESS_ID }}
          private_key: ${{ secrets.ACCESS_TOKEN }}

      # Configure npm authentication for GitHub Packages
      - name: Configure npm authentication
        run: |
          echo "@vannatta-software:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ steps.get-token.outputs.token }}" >> ~/.npmrc

      - name: Calculate Token Length
        run: |
          echo "token_length=${#token}" >> $GITHUB_ENV
        env:
          token: ${{ steps.get-token.outputs.token }}

      # Debug Token Length
      - name: Debug Token Length
        run: |
          echo "Token length: ${{ env.token_length }}"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build TypeScript project
      - name: Build project
        run: npm run build

      # Publish to GitHub Packages
      - name: Publish to GitHub Packages
        run: npm publish
