name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
      - monorepo
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Configure npm authentication
        run: |
          echo "@vannatta-software:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.DEPLOY_TOKEN }}" >> ~/.npmrc

      - name: Install dependencies
        run: |
          npm install

      # - name: Publish core package
      #   run: |
      #     cd packages/core
      #     npm publish --access public

      # - name: Publish domain package
      #   run: |
      #     cd packages/domain
      #     npm publish --access public

      - name: Publish frontend package
        run: |
          cd packages/frontend
          npm publish --access public
