name: Run Tests for All Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests for core package
        run: |
          cd packages/core
          npm run test

      - name: Run tests for domain package
        run: |
          cd packages/domain
          npm run test

      # - name: Run tests for frontend package
      #   run: |
      #     cd packages/frontend
      #     npm run test
